#!/bin/sh -f
# ****************************************************************************
#
# This file was generated by Vivado, it's been modified to only run vhdlan
# on the Xilinx generated IP.  It only runs on the top files, the Xilinx
# simulation libraries are pre-generated and pointed at by the synopsys_sim.setup
# file, this step is done by the setup.sh script
#
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Tue Mar 06 14:45:07 PST 2018
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************

# installation path setting
bin_path="/import/pa-tools/synopsys/vcs-mx/N-2017.12-1/bin"

# directory path for design sources and include directories (if any) wrt this path
origin_dir="."

# set vhdlan command line args
vhdlan_opts="-full64"

# set vlogan command line args
vlogan_opts="-full64 -kdb"

# compile design source files
$bin_path/vhdlan $vhdlan_opts -work xil_defaultlib -f bigIP.vivado.f 2>&1 | tee -a vhdlan.log

#$bin_path/vlogan $vlogan_opts -sverilog -Xcheck_p1800_2009=char -work xil_defaultlib  +incdir+/import/pa-tools/xilinx/Vivado/2017.4/data/xilinx_vip/include \
#"$origin_dir/../../../../ip.srcs/sources_1/new/accum_tb.sv" \
#2>&1 | tee -a vlogan.log


# compile glbl module
#$bin_path/vlogan $vlogan_opts +v2k -work xil_defaultlib "glbl.v" 2>&1 | tee -a vlogan.log
